name = "Sudoku3D"
uuid = "00f5a8a1-c6ac-4e59-b637-ea595a587982"
authors = ["Andreas Bøgh Poulsen"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
